# Knot Project Configuration

[document]
main = "main.knot"
includes = [
    "r.knot",
    "r-plots.knot",
    "r-ggplot.knot",
    "py.knot",
    "py-plots.knot",
    "chunk-options.knot"
]

[helpers]
typst = "lib/knot.typ"
