//! Side-channel communication for language executors
//!
//! Instead of parsing stdout for magic markers (fragile), we use a separate
//! channel: a temporary JSON file whose path is passed via environment variable.
//!
//! This is more robust and works identically for R, Python, Julia, etc.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// A JSON value that can be either a plain string or an array of strings.
///
/// R serializes scalar values as plain strings with `auto_unbox = TRUE` (our
/// default), so in practice the `String` variant is produced by R for scalar
/// fields. The `Vec` variant handles any residual arrays (e.g. multi-line
/// call stacks) and acts as a defensive fallback.
///
/// `#[serde(untagged)]` tries `String` first, then `Vec`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum StringOrVec {
    String(String),
    Vec(Vec<String>),
}

impl std::fmt::Display for StringOrVec {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StringOrVec::String(s) => write!(f, "{}", s),
            StringOrVec::Vec(v) => write!(f, "{}", v.join("\n")),
        }
    }
}

impl StringOrVec {
    pub fn as_str(&self) -> &str {
        match self {
            StringOrVec::String(s) => s,
            StringOrVec::Vec(v) => {
                if v.is_empty() {
                    ""
                } else {
                    &v[0]
                }
            }
        }
    }
}

/// Metadata about outputs generated by code execution
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum OutputMetadata {
    /// A plot/figure that was saved to a file
    Plot {
        path: PathBuf,
        format: StringOrVec, // "svg", "png", "pdf"
    },
    /// A DataFrame that was serialized to CSV
    DataFrame { path: PathBuf },
    /// Plain text output (fallback)
    Text { content: StringOrVec },
}

/// A warning captured during code execution
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RuntimeWarning {
    pub message: StringOrVec,
    pub call: Option<StringOrVec>,
    /// Source line number where the warning was triggered.
    ///
    /// Not yet implemented: R does not populate this field and the
    /// Typst backend does not display it. Reserved for future use.
    pub line: Option<usize>,
}

/// A fatal error captured during code execution
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RuntimeError {
    pub message: Option<StringOrVec>,
    pub call: Option<StringOrVec>,
    /// Source line number where the error was triggered.
    ///
    /// Not yet implemented: R does not populate this field and the
    /// Typst backend does not display it. Reserved for future use.
    pub line: Option<usize>,
    #[serde(default)]
    pub traceback: Vec<String>,
}

impl std::fmt::Display for RuntimeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let msg = self.message.as_ref().map(|m| m.to_string()).unwrap_or_else(|| "Unknown error".to_string());
        write!(f, "{}", msg)
    }
}

/// Root structure for metadata passed via side-channel
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct KnotMetadata {
    #[serde(default)]
    pub results: Vec<OutputMetadata>,
    #[serde(default)]
    pub warnings: Vec<RuntimeWarning>,
    #[serde(default)]
    pub error: Option<RuntimeError>,
}

/// Side-channel for passing metadata from language runtime to Rust
pub struct SideChannel {
    metadata_file: PathBuf,
}

impl SideChannel {
    /// Create a new side-channel with a temporary metadata file
    pub fn new() -> Result<Self> {
        let temp_dir = std::env::temp_dir();
        let uuid = uuid::Uuid::new_v4();
        let metadata_file = temp_dir.join(format!("knot_meta_{}.json", uuid));

        Ok(Self { metadata_file })
    }

    /// Read metadata written by language runtime
    pub fn read_metadata(&self) -> Result<KnotMetadata> {
        if !self.metadata_file.exists() {
            return Ok(KnotMetadata::default());
        }

        let content =
            std::fs::read_to_string(&self.metadata_file).context("Failed to read metadata file")?;

        if content.trim().is_empty() {
            return Ok(KnotMetadata::default());
        }

        // Try to parse as the new structured format
        if let Ok(meta) = serde_json::from_str::<KnotMetadata>(&content) {
            return Ok(meta);
        }

        // Fallback: try to parse as Vec<OutputMetadata> for backward compatibility
        if let Ok(results) = serde_json::from_str::<Vec<OutputMetadata>>(&content) {
            return Ok(KnotMetadata {
                results,
                ..Default::default()
            });
        }

        // Final fallback: if parsing still fails, return empty metadata instead of bailing out.
        // This prevents a single malformed JSON from stopping the whole compilation.
        log::warn!(
            "Malformed side-channel JSON. Using empty metadata. Content: {}",
            content
        );
        Ok(KnotMetadata::default())
    }

    /// Get the path to the metadata file
    pub fn path(&self) -> &PathBuf {
        &self.metadata_file
    }

    /// Clean up temporary metadata file
    pub fn cleanup(&self) {
        let _ = std::fs::remove_file(&self.metadata_file);
    }

    /// Get the path to the metadata file (for testing)
    #[cfg(test)]
    pub fn metadata_file(&self) -> &PathBuf {
        &self.metadata_file
    }
}

impl Drop for SideChannel {
    fn drop(&mut self) {
        self.cleanup();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_side_channel() {
        let channel = SideChannel::new().unwrap();
        assert!(
            channel
                .metadata_file
                .to_string_lossy()
                .contains("knot_meta_")
        );
    }

    #[test]
    fn test_read_empty_metadata() {
        let channel = SideChannel::new().unwrap();
        let metadata = channel.read_metadata().unwrap();
        assert_eq!(metadata.results.len(), 0);
    }

    #[test]
    fn test_read_metadata_plot() {
        let channel = SideChannel::new().unwrap();

        // New structured format
        let metadata = KnotMetadata {
            results: vec![OutputMetadata::Plot {
                path: PathBuf::from("/tmp/plot.svg"),
                format: StringOrVec::String("svg".to_string()),
            }],
            ..Default::default()
        };

        let json = serde_json::to_string(&metadata).unwrap();
        std::fs::write(&channel.metadata_file, json).unwrap();

        // Read back
        let read_metadata = channel.read_metadata().unwrap();
        assert_eq!(read_metadata.results.len(), 1);

        match &read_metadata.results[0] {
            OutputMetadata::Plot { path, format } => {
                assert_eq!(path, &PathBuf::from("/tmp/plot.svg"));
                assert_eq!(format.to_string(), "svg");
            }
            _ => panic!("Expected Plot metadata"),
        }
    }

    #[test]
    fn test_read_legacy_metadata() {
        let channel = SideChannel::new().unwrap();

        // Old list format
        let results = vec![OutputMetadata::Text {
            content: StringOrVec::String("Legacy".to_string()),
        }];

        let json = serde_json::to_string(&results).unwrap();
        std::fs::write(&channel.metadata_file, json).unwrap();

        // Should still be readable via fallback
        let read_metadata = channel.read_metadata().unwrap();
        assert_eq!(read_metadata.results.len(), 1);
        assert_eq!(
            read_metadata.results[0],
            OutputMetadata::Text {
                content: StringOrVec::String("Legacy".to_string()),
            }
        );
    }
}
