//! Side-channel communication for language executors
//!
//! Instead of parsing stdout for magic markers (fragile), we use a separate
//! channel: a temporary JSON file whose path is passed via environment variable.
//!
//! This is more robust and works identically for R, Python, Julia, etc.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Metadata about outputs generated by code execution
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum OutputMetadata {
    /// A plot/figure that was saved to a file
    Plot {
        path: PathBuf,
        format: String, // "svg", "png", "pdf"
    },
    /// A DataFrame that was serialized to CSV
    DataFrame { path: PathBuf },
    /// Plain text output (fallback)
    Text { content: String },
}

/// A warning captured during code execution
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RuntimeWarning {
    pub message: String,
    pub call: Option<String>,
    pub line: Option<usize>,
}

/// A fatal error captured during code execution
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RuntimeError {
    pub message: String,
    pub call: Option<String>,
    pub line: Option<usize>,
    pub traceback: Vec<String>,
}

/// Root structure for metadata passed via side-channel
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct KnotMetadata {
    #[serde(default)]
    pub results: Vec<OutputMetadata>,
    #[serde(default)]
    pub warnings: Vec<RuntimeWarning>,
    #[serde(default)]
    pub error: Option<RuntimeError>,
}

/// Side-channel for passing metadata from language runtime to Rust
pub struct SideChannel {
    metadata_file: PathBuf,
}

impl SideChannel {
    /// Create a new side-channel with a temporary metadata file
    pub fn new() -> Result<Self> {
        let temp_dir = std::env::temp_dir();
        let uuid = uuid::Uuid::new_v4();
        let metadata_file = temp_dir.join(format!("knot_meta_{}.json", uuid));

        Ok(Self { metadata_file })
    }

    /// Read metadata written by language runtime
    pub fn read_metadata(&self) -> Result<KnotMetadata> {
        if !self.metadata_file.exists() {
            return Ok(KnotMetadata::default());
        }

        let content =
            std::fs::read_to_string(&self.metadata_file).context("Failed to read metadata file")?;

        if content.trim().is_empty() {
            return Ok(KnotMetadata::default());
        }

        // Try to parse as the new structured format
        match serde_json::from_str::<KnotMetadata>(&content) {
            Ok(meta) => Ok(meta),
            Err(e) => {
                log::debug!("Structured metadata parsing failed: {}. Content: {}", e, content);
                // Fallback: try to parse as Vec<OutputMetadata> for backward compatibility
                // (some old tests or simpler executors might still use the old format)
                let results: Vec<OutputMetadata> = serde_json::from_str(&content)
                    .context("Failed to parse metadata JSON (neither structured nor list format)")?;
                Ok(KnotMetadata {
                    results,
                    ..Default::default()
                })
            }
        }
    }

    /// Get the path to the metadata file
    pub fn path(&self) -> &PathBuf {
        &self.metadata_file
    }

    /// Clean up temporary metadata file
    pub fn cleanup(&self) {
        let _ = std::fs::remove_file(&self.metadata_file);
    }

    /// Get the path to the metadata file (for testing)
    #[cfg(test)]
    pub fn metadata_file(&self) -> &PathBuf {
        &self.metadata_file
    }
}

impl Drop for SideChannel {
    fn drop(&mut self) {
        self.cleanup();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_side_channel() {
        let channel = SideChannel::new().unwrap();
        assert!(
            channel
                .metadata_file
                .to_string_lossy()
                .contains("knot_meta_")
        );
    }

    #[test]
    fn test_read_empty_metadata() {
        let channel = SideChannel::new().unwrap();
        let metadata = channel.read_metadata().unwrap();
        assert_eq!(metadata.results.len(), 0);
    }

    #[test]
    fn test_read_metadata_plot() {
        let channel = SideChannel::new().unwrap();

        // New structured format
        let metadata = KnotMetadata {
            results: vec![OutputMetadata::Plot {
                path: PathBuf::from("/tmp/plot.svg"),
                format: "svg".to_string(),
            }],
            ..Default::default()
        };

        let json = serde_json::to_string(&metadata).unwrap();
        std::fs::write(&channel.metadata_file, json).unwrap();

        // Read back
        let read_metadata = channel.read_metadata().unwrap();
        assert_eq!(read_metadata.results.len(), 1);

        match &read_metadata.results[0] {
            OutputMetadata::Plot { path, format } => {
                assert_eq!(path, &PathBuf::from("/tmp/plot.svg"));
                assert_eq!(format, "svg");
            }
            _ => panic!("Expected Plot metadata"),
        }
    }

    #[test]
    fn test_read_legacy_metadata() {
        let channel = SideChannel::new().unwrap();

        // Old list format
        let results = vec![OutputMetadata::Text {
            content: "Legacy".to_string(),
        }];

        let json = serde_json::to_string(&results).unwrap();
        std::fs::write(&channel.metadata_file, json).unwrap();

        // Should still be readable via fallback
        let read_metadata = channel.read_metadata().unwrap();
        assert_eq!(read_metadata.results.len(), 1);
        assert_eq!(
            read_metadata.results[0],
            OutputMetadata::Text {
                content: "Legacy".to_string()
            }
        );
    }
}
