//! Side-channel communication for language executors
//!
//! Instead of parsing stdout for magic markers (fragile), we use a separate
//! channel: a temporary JSON file whose path is passed via environment variable.
//!
//! This is more robust and works identically for R, Python, Julia, etc.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Metadata about outputs generated by code execution
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum OutputMetadata {
    /// A plot/figure that was saved to a file
    Plot {
        path: PathBuf,
        format: String, // "svg", "png", "pdf"
    },
    /// A DataFrame that was serialized to CSV
    DataFrame { path: PathBuf },
    /// Plain text output (fallback)
    Text { content: String },
}

/// Side-channel for passing metadata from language runtime to Rust
///
/// Usage:
/// ```
/// # use knot_core::executors::side_channel::SideChannel;
/// let channel = SideChannel::new().unwrap();
/// channel.setup_env().unwrap();
///
/// // Execute code (R/Python writes to KNOT_METADATA_FILE)
/// // executor.run(code)?;
///
/// // Read metadata
/// let outputs = channel.read_metadata().unwrap();
/// // channel.cleanup() called automatically via Drop
/// ```
pub struct SideChannel {
    metadata_file: PathBuf,
}

impl SideChannel {
    /// Create a new side-channel with a temporary metadata file
    pub fn new() -> Result<Self> {
        let temp_dir = std::env::temp_dir();
        let uuid = uuid::Uuid::new_v4();
        let metadata_file = temp_dir.join(format!("knot_meta_{}.json", uuid));

        Ok(Self { metadata_file })
    }

    /// Setup environment variable for language runtime to write to
    ///
    /// # Safety
    /// This is safe because:
    /// - We own the SideChannel instance (single-threaded context)
    /// - The env var is only read by child processes we spawn
    /// - No concurrent env var modifications in our architecture
    pub fn setup_env(&self) -> Result<()> {
        unsafe {
            std::env::set_var("KNOT_METADATA_FILE", &self.metadata_file);
        }
        Ok(())
    }

    /// Read metadata written by language runtime
    pub fn read_metadata(&self) -> Result<Vec<OutputMetadata>> {
        if !self.metadata_file.exists() {
            return Ok(vec![]);
        }

        let content = std::fs::read_to_string(&self.metadata_file)
            .context("Failed to read metadata file")?;

        if content.trim().is_empty() {
            return Ok(vec![]);
        }

        let metadata: Vec<OutputMetadata> = serde_json::from_str(&content)
            .context("Failed to parse metadata JSON")?;

        Ok(metadata)
    }

    /// Get the path to the metadata file
    pub fn path(&self) -> &PathBuf {
        &self.metadata_file
    }

    /// Clean up temporary metadata file
    pub fn cleanup(&self) {
        let _ = std::fs::remove_file(&self.metadata_file);
    }

    /// Get the path to the metadata file (for testing)
    #[cfg(test)]
    pub fn metadata_file(&self) -> &PathBuf {
        &self.metadata_file
    }
}

impl Drop for SideChannel {
    fn drop(&mut self) {
        self.cleanup();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_side_channel() {
        let channel = SideChannel::new().unwrap();
        assert!(channel.metadata_file.to_string_lossy().contains("knot_meta_"));
    }

    #[test]
    fn test_setup_env() {
        let channel = SideChannel::new().unwrap();
        channel.setup_env().unwrap();

        let env_value = std::env::var("KNOT_METADATA_FILE").unwrap();
        assert_eq!(env_value, channel.metadata_file.to_string_lossy());
    }

    #[test]
    fn test_read_empty_metadata() {
        let channel = SideChannel::new().unwrap();
        let metadata = channel.read_metadata().unwrap();
        assert_eq!(metadata.len(), 0);
    }

    #[test]
    fn test_read_metadata_plot() {
        let channel = SideChannel::new().unwrap();

        // Simulate R/Python writing metadata
        let metadata = vec![OutputMetadata::Plot {
            path: PathBuf::from("/tmp/plot.svg"),
            format: "svg".to_string(),
        }];

        let json = serde_json::to_string(&metadata).unwrap();
        std::fs::write(&channel.metadata_file, json).unwrap();

        // Read back
        let read_metadata = channel.read_metadata().unwrap();
        assert_eq!(read_metadata.len(), 1);

        match &read_metadata[0] {
            OutputMetadata::Plot { path, format } => {
                assert_eq!(path, &PathBuf::from("/tmp/plot.svg"));
                assert_eq!(format, "svg");
            }
            _ => panic!("Expected Plot metadata"),
        }
    }

    #[test]
    fn test_read_metadata_multiple_outputs() {
        let channel = SideChannel::new().unwrap();

        let metadata = vec![
            OutputMetadata::Text {
                content: "Hello".to_string(),
            },
            OutputMetadata::DataFrame {
                path: PathBuf::from("/tmp/data.csv"),
            },
            OutputMetadata::Plot {
                path: PathBuf::from("/tmp/plot.svg"),
                format: "svg".to_string(),
            },
        ];

        let json = serde_json::to_string(&metadata).unwrap();
        std::fs::write(&channel.metadata_file, json).unwrap();

        let read_metadata = channel.read_metadata().unwrap();
        assert_eq!(read_metadata.len(), 3);
    }

    #[test]
    fn test_cleanup() {
        let channel = SideChannel::new().unwrap();
        let path = channel.metadata_file.clone();

        std::fs::write(&path, "test").unwrap();
        assert!(path.exists());

        channel.cleanup();
        assert!(!path.exists());
    }

    #[test]
    fn test_cleanup_on_drop() {
        let path = {
            let channel = SideChannel::new().unwrap();
            let p = channel.metadata_file.clone();
            std::fs::write(&p, "test").unwrap();
            assert!(p.exists());
            p
            // Drop called here
        };

        // File should be cleaned up
        assert!(!path.exists());
    }
}
