// ============================================
// Knot Typst Package
// ============================================
//
// This package provides helper functions for displaying code chunks
// and outputs generated by the Knot compiler.
//
// IMPORTANT: This file should contain ONLY utility functions,
// not document configuration (Codly, figure numbering, etc.).
// Document configuration belongs in your main.knot file.

/// Visual styles for chunk execution states (live preview only — not in final PDF).
/// These appear during `knot watch --preview` and VS Code preview when chunks are
/// pending execution, recently modified, or inert due to an upstream error.
/// Override entries here to customize the preview feedback; chunk presentation
/// styles (background, inset, etc.) belong in knot.toml or chunk options instead.
#let knot-state-styles = (
  pending: (
    stroke: 2pt + rgb("#f97316"),
  ),
  modified: (
    stroke: 5pt + rgb("#fcd34d"),
  ),
  "modified-cascade": (
    stroke: 0.5pt + rgb("#fcd34d"),
  ),
  inert: (
    overlay-fill: white.transparentize(40%),
  ),
)

#let code-chunk(
  code: none,
  output: none,
  warnings: (),
  errors: (),
  warnings-position: "below", // "below" or "inline"
  layout: none, // Optional: only used when both code and output are present
  gutter: 0.5em,
  code-background: none,
  code-stroke: none,
  code-radius: 0pt,
  code-inset: 0pt,
  output-background: rgb(255, 255, 255),
  output-stroke: none,
  output-radius: 0pt,
  output-inset: 0pt,
  warning-background: rgb("#fff4ce"),
  warning-stroke: 1pt + rgb("#facc15"),
  warning-radius: 2pt,
  warning-inset: 0.5em,
  width-ratio: "1:1",
  align: none,
  is-inert: false,
  is-pending: false,
  is-modified: false,
  is-modified-cascade: false,
  state-styles: knot-state-styles,
  ..rest,
) = {
  // Ensure warnings and errors are arrays (defensive check)
  let warnings = if type(warnings) == array { warnings } else if warnings == none { () } else { (warnings,) }
  let errors = if type(errors) == array { errors } else if errors == none { () } else { (errors,) }

  // Parse width-ratio for horizontal layout
  let ratio-parts = width-ratio.split(":")
  let left-ratio = if ratio-parts.len() >= 1 { float(ratio-parts.at(0)) } else { 1.0 }
  let right-ratio = if ratio-parts.len() >= 2 { float(ratio-parts.at(1)) } else { 1.0 }

  // Wrap code in styled block
  let code-block = if code != none {
    // Visual state borders: driven by state-styles dict (customizable via knot-state-styles).
    let effective-stroke = if is-pending { state-styles.pending.stroke } else if is-modified {
      state-styles.modified.stroke
    } else if is-modified-cascade { state-styles.at("modified-cascade").stroke } else { code-stroke }
    let b = block(
      fill: code-background,
      stroke: effective-stroke,
      radius: code-radius,
      inset: code-inset,
      width: 100%,
    )[#code]

    if is-inert {
      // Use a clipping block to contain the overlay perfectly
      block(width: 100%, clip: true, radius: code-radius)[
        #b
        #place(top + left, rect(width: 100%, height: 5000pt, fill: state-styles.inert.overlay-fill))
      ]
    } else {
      b
    }
  } else { none }

  // Wrap output in styled block
  let output-block = if output != none {
    block(
      fill: output-background,
      stroke: output-stroke,
      radius: output-radius,
      inset: output-inset,
      width: 100%,
    )[#output]
  } else { none }

  // Warning blocks (reused for both inline and below positioning)
  let warning-blocks = warnings.map(w => block(
    fill: warning-background,
    stroke: warning-stroke,
    radius: warning-radius,
    inset: warning-inset,
    width: 100%,
  )[
    #set text(fill: rgb("#854d0e"), size: 0.85em)
    *Warning:* #w
  ])

  // Layout based on what's being displayed
  let main-content = if code == none and output != none {
    // Only output: single column
    if warnings-position == "inline" and warning-blocks.len() > 0 {
      stack(dir: ttb, spacing: 0.5em, output-block, ..warning-blocks)
    } else {
      output-block
    }
  } else if output == none and code != none {
    // Only code: single column (warnings not applicable here)
    code-block
  } else if code != none and output != none {
    // Both code and output: use layout
    if layout == "vertical" {
      if warnings-position == "inline" and warning-blocks.len() > 0 {
        stack(dir: ttb, spacing: gutter, code-block, output-block, ..warning-blocks)
      } else {
        stack(dir: ttb, spacing: gutter, code-block, output-block)
      }
    } else {
      // horizontal (default when layout is none or "horizontal")
      if warnings-position == "inline" and warning-blocks.len() > 0 {
        let right-col = stack(dir: ttb, spacing: gutter, output-block, ..warning-blocks)
        grid(
          columns: (left-ratio * 1fr, right-ratio * 1fr),
          gutter: gutter,
          code-block, right-col,
        )
      } else {
        grid(
          columns: (left-ratio * 1fr, right-ratio * 1fr),
          gutter: gutter,
          code-block, output-block,
        )
      }
    }
  } else { none }

  // Assemble final content
  if main-content == none and warnings.len() == 0 and errors.len() == 0 {
    return none
  }

  // Warnings below: appended after main-content (inline: already embedded above)
  let below-warnings = if warnings-position == "inline" { () } else { warning-blocks }

  stack(
    dir: ttb,
    spacing: 0.5em,
    main-content,
    ..below-warnings,
    ..errors.map(e => block(
      fill: rgb("#ef4444"), // Solid red
      stroke: 1pt + rgb("#b91c1c"),
      radius: 4pt,
      inset: 1em,
      width: 100%,
    )[
      #set text(fill: white, size: 0.95em)
      #e
    ]),
  )
}
