//! Generate default knot.toml template with all options documented
//!
//! This tool uses the option_metadata() method auto-generated by the
//! define_options! macro to produce a comprehensive knot.toml template.
//!
//! Run with: cargo run --example generate_defaults

use knot_core::parser::{ChunkOptions, OptionMetadata};
use std::fs;

fn main() {
    println!("🔍 Extracting ChunkOptions metadata...\n");

    let options = ChunkOptions::option_metadata();
    println!("✅ Found {} options\n", options.len());

    // Generate knot.toml template
    let output = generate_knot_toml(&options);

    // Write to templates/minimal/knot.toml
    let output_path = "../../templates/minimal/knot.toml";
    fs::write(output_path, &output).expect("Failed to write knot.toml template");

    println!("✅ Generated {}\n", output_path);
    println!("Preview:");
    println!("{}", output.lines().take(30).collect::<Vec<_>>().join("\n"));
}

fn generate_knot_toml(options: &[OptionMetadata]) -> String {
    let mut output = String::new();

    output.push_str("# Knot Project Configuration\n\n");
    output.push_str("[document]\n");
    output.push_str("main = \"main.knot\"\n");
    output.push_str("# includes = [\"chapter1.knot\", \"chapter2.knot\"]\n\n");

    output.push_str("[helpers]\n");
    output.push_str("# Typst helper functions (for rendering R/Python output)\n");
    output.push_str("typst = \"lib/knot.typ\"\n\n");

    output.push_str("# ============================================\n");
    output.push_str("# Default values for chunk options\n");
    output.push_str("# ============================================\n");
    output.push_str("#\n");
    output.push_str("# These defaults apply to all chunks unless overridden in\n");
    output.push_str("# individual chunk headers using YAML syntax:\n");
    output.push_str("#\n");
    output.push_str("#   ```{r}\n");
    output.push_str("#   #| echo: false\n");
    output.push_str("#   #| fig-width: 10\n");
    output.push_str("#   ...\n");
    output.push_str("#   ```\n");
    output.push_str("#\n");
    output.push_str("# Uncomment and modify the options below to change defaults.\n\n");

    output.push_str("[chunk-defaults]\n\n");

    // Group options by category
    let mut execution_opts = Vec::new();
    let mut graphics_opts = Vec::new();
    let mut presentation_opts = Vec::new();

    for opt in options {
        // Only include [val] and [opt] options (configurable in knot.toml)
        if opt.kind != "val" && opt.kind != "opt" {
            continue;
        }

        if opt.name.starts_with("fig_") || opt.name == "dpi" {
            graphics_opts.push(opt);
        } else if opt.name.starts_with("code_")
            || opt.name.starts_with("output_")
            || opt.name == "layout"
            || opt.name == "gutter"
            || opt.name == "width_ratio"
            || opt.name == "align"
        {
            presentation_opts.push(opt);
        } else {
            execution_opts.push(opt);
        }
    }

    // Execution options
    output.push_str("# === Execution Options ===\n\n");
    for opt in &execution_opts {
        add_option(&mut output, opt);
    }

    output.push_str("# === Graphics Options ===\n\n");
    for opt in &graphics_opts {
        add_option(&mut output, opt);
    }

    output.push_str("# === Presentation Options ===\n\n");
    for opt in &presentation_opts {
        add_option(&mut output, opt);
    }

    output
}

fn add_option(output: &mut String, opt: &OptionMetadata) {
    // Add documentation (trim leading/trailing space)
    let doc = opt.doc.trim();
    if !doc.is_empty() {
        output.push_str(&format!("# {}\n", doc));
    }

    // Format default value
    let formatted_default = format_default_value(opt.default_value, opt.name);

    // Add commented option line
    output.push_str(&format!("# {} = {}\n", opt.serde_name(), formatted_default));
    output.push('\n');
}

fn format_default_value(default: &str, name: &str) -> String {
    // Handle common cases
    if default == "true" || default == "false" {
        return default.to_string();
    }

    if default == "None" {
        // For optional values, show reasonable examples based on field name
        return match name {
            "gutter" => "\"1em\"".to_string(),
            "code_background" | "output_background" => "\"#f5f5f5\"".to_string(),
            "code_stroke" | "output_stroke" => "\"1pt solid gray\"".to_string(),
            "code_radius" | "output_radius" => "\"4pt\"".to_string(),
            "code_inset" | "output_inset" => "\"8pt\"".to_string(),
            "width_ratio" => "\"1:1\"".to_string(),
            "align" => "\"left\"".to_string(),
            _ => "\"value\"".to_string(),
        };
    }

    // String literals
    if default.ends_with(".to_string()") {
        return default.replace(".to_string()", "");
    }

    // Numeric values
    if default.parse::<f64>().is_ok() || default.parse::<u32>().is_ok() {
        return default.to_string();
    }

    default.to_string()
}
