// ============================================
// Knot Typst Package
// ============================================
//
// This package provides helper functions for displaying code chunks
// and outputs generated by the Knot compiler.
//
// IMPORTANT: This file should contain ONLY utility functions,
// not document configuration (Codly, figure numbering, etc.).
// Document configuration belongs in your main.knot file.

#let code-chunk(
  input: none,
  output: none,
  layout: none, // Optional: only used when both input and output are present
  gutter: 0.5em,
  code-background: none,
  code-stroke: none,
  code-radius: 0pt,
  code-inset: 0pt,
  output-background: rgb(255, 255, 255),
  output-stroke: none,
  output-radius: 0pt,
  output-inset: 0pt,
  width-ratio: "1:1",
  align: none,
  ..rest,
) = {
  // Parse width-ratio for horizontal layout
  let ratio-parts = width-ratio.split(":")
  let left-ratio = if ratio-parts.len() >= 1 { float(ratio-parts.at(0)) } else { 1.0 }
  let right-ratio = if ratio-parts.len() >= 2 { float(ratio-parts.at(1)) } else { 1.0 }

  // Wrap input in styled block
  let code-block = if input != none {
    block(
      fill: code-background,
      stroke: code-stroke,
      radius: code-radius,
      inset: code-inset,
      width: 100%,
    )[#input]
  } else { none }

  // Wrap output in styled block
  let output-block = if output != none {
    block(
      fill: output-background,
      stroke: output-stroke,
      radius: output-radius,
      inset: output-inset,
      width: 100%,
    )[#output]
  } else { none }

  // Layout based on what's being displayed
  if input == none and output != none {
    // Only output: single column
    output-block
  } else if output == none and input != none {
    // Only input: single column
    code-block
  } else if input != none and output != none {
    // Both input and output: use layout
    if layout == "vertical" {
      stack(
        dir: ttb,
        spacing: gutter,
        code-block,
        output-block,
      )
    } else {
      // horizontal (default when layout is none or "horizontal")
      grid(
        columns: (left-ratio * 1fr, right-ratio * 1fr),
        gutter: gutter,
        code-block, output-block,
      )
    }
  }
  // If both are none, display nothing
}
